version: "3"


services:
  
  nothing:
    container_name: pcf_c
    image: pcf_i
    build: .
    ports:
      - 80:80
    restart: always

    volumes:
      - . :/var/www/html
    environment:
      - MYSQL_DATABASE=pcf
      - MYSQL_USER=mydb
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  db:
    image: mysql
    hostname: sqldb
    environment:
      - MYSQL_DATABASE=pcf
      - MYSQL_USER=mydb
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 82:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306